src/dcastello/TraventyBundle/Entity/Excursion.php
<?php

namespace dcastello\TraventyBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * dcastello\TraventyBundle\Entity\TravelerEvent
 * 
 * @ORM\Table(name="excursion")
 * @ORM\Entity(repositoryClass="dcastello\TraventyBundle\Entity\ExcursionRepository")
 */
class Excursion extends Event
{
    /**
     * @ORM\ManyToOne(targetEntity="Traveler", inversedBy="excursions")
     * @ORM\JoinColumn(name="traveler_id", referencedColumnName="id")
     */
    private $traveler;

    public function setTraveler(Traveler $traveler = null)
    {
        $this->traveler = $traveler;
    }

    public function getTraveler()
    {
        return $this->traveler;
    }

    public function getType()
    {
        return 'EXCURSION';
    }

}

src/dcastello/TraventyBundle/Resources/views/layout-admin.html.twig
{% extends "::base.html.twig" %}

{% block traventy %}
<body id="{% block id '' %}">
  
<div class="container">

  {% block header %}
  <header class="row">

    <div class="navbar span12">
      <div class="navbar-inner">
        <div class="container" style="width: auto">

        <a class="brand" href="#">Traventy</a>
        <ul class="nav">
          <li class="active"><a href="{{ path('admin_homepage') }}">Home</a></li>
          <li><a href="{{ path('admin_activity') }}">Activities</a></li>
          <li><a href="{{ path('admin_resource') }}">Resources</a></li>
        </ul>
        
        </div>
      </div>
    </div>      
      
  </header>    
  {% endblock %}

  {% block content %}{% endblock %}
  
  <footer>
  {% block footer %}
    <p>&copy; Traventy</p>
  {% endblock %}
  </footer>  
  
</div>

{% block javascripts %}{% endblock %}

</body>
{% endblock %}

src/dcastello/TraventyBundle/Resources/views/layout.html.twig
{% extends "::base.html.twig" %}

{% block traventy %}
<body id="{% block id '' %}">
  
<div class="container">
   
  {% block header %}
  <header class="row">

  <div class="navbar span12">
    <div class="navbar-inner">
      <div class="container" style="width: auto;">
               
      <a class="brand" href="#">Traventy</a>
      <ul class="nav">
        <li class="active"><a href="{{ path('homepage') }}">Home</a></li>
        <li><a href="{{ path('travels') }}">Travels</a></li>
        <li><a href="{{ path('excursions') }}">Excursions</a></li>
        <li><a href="{{ path('activity') }}">Activities</a></li>
        <li><a href="{{ path('resource') }}">Resources</a></li>
      </ul>

      <ul class="nav pull-right">
        {% if is_granted('IS_AUTHENTICATED_FULLY') %}
          <li><a href="{{ path(app.user.type|lower ~ '_home', { 'username' : app.user.username }) }}">Account</a></li>
          <li class="divider-vertical"></li>
          <li><a href="{{ path('user_logout') }}">Logout</a></li>
        {% else %}
          <li><a href="{{ path('user_login') }}">Login</a></li>
          <li class="divider-vertical"></li>
        {% endif %}
      </ul>        
       
      </div>
    </div>
  </div>
      
  </header>
  {% endblock %}

  {% block content %}{% endblock %}
    
  {% block footer %}
  <footer>
    <p>&copy; Traventy</p>
  </footer>
  {% endblock %}
  
</div>

{% block javascripts %}{% endblock %}

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-30432909-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

</body>
{% endblock %}