src/dcastello/TraventyBundle/Entity/Activity.php
<?php

namespace dcastello\TraventyBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * dcastello\TraventyBundle\Entity\Activity
 *
 * @ORM\Table(name="activity")
 * @ORM\Entity(repositoryClass="dcastello\TraventyBundle\Entity\ActivityRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Activity
{
    const DEFAULT_COUNTRY = 'Spain';

    /**
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;
    /**
     * @ORM\Column(name="name", type="string", length=255)
     * @Assert\NotBlank()
     * @Assert\MinLength(
     *     limit=5,
     *     message="The minimum characters are {{ limit }}"
     * )
     */
    private $name;
    /**
     * @ORM\ManyToOne(targetEntity="City")
     * @ORM\JoinColumn(name="city_id", referencedColumnName="id")
     */
    private $city;
    /**
     * @ORM\Column(name="country", type="string", length=255, nullable=true)
     */
    private $country;
    /**
     * @ORM\Column(name="description", type="text")
     * @Assert\NotBlank()
     */
    private $description;
    /**
     * @ORM\Column(name="date", type="datetime", nullable=true)
     * @Assert\DateTime
     */
    private $date;
    /**
     * @ORM\ManyToMany(targetEntity="Traveler", mappedBy="favoritesActivities")
     */
    private $favoritesTravelers;
    /**
     * @ORM\OneToMany(targetEntity="ImageActivity", mappedBy="activity", orphanRemoval=true, cascade={"all"})
     */
    private $images;

    public function __construct()
    {
        $this->favoritesTravelers = new ArrayCollection();
        $this->images = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->getName();
    }

    public function getFavoritesTravelers()
    {
        return $this->favoritesTravelers;
    }

    public function addFavoriteTraveler(Traveler $traveler)
    {
        if (!$this->favoritesTravelers->contains($traveler)) {
            $this->favoritesTravelers->add($traveler);
        }
    }

    public function getImages()
    {
        return $this->images;
    }

    public function setImages(Collection $images)
    {
        foreach ($images as $image) {
            $image->setActivity($this);
        }
        $this->images = $images;
    }

    public function addImage(ImageActivity $image)
    {
        if (!$this->images->contains($image)) {
            $this->images->add($image);
            $image->setActivity($this);
        }
    }

    public function removeImage(ImageActivity $image)
    {
        if ($this->images->removeElement($image)) {
            $image->setActivity(null);
        }
    }

    public function getRandomImage()
    {
        $image = $this->getImages()->first();
        if ($image) {
            return $image;
        }
        return null;
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     */
    public function setName($name)
    {
        $this->name = $name;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set city
     *
     * @param string $city
     */
    public function setCity($city)
    {
        $this->city = $city;
    }

    /**
     * Get city
     *
     * @return string
     */
    public function getCity()
    {
        return $this->city;
    }

    /**
     * Set country
     *
     * @param string $country
     */
    public function setCountry($country)
    {
        $this->country = $country;
    }

    /**
     * Get country
     *
     * @return string
     */
    public function getCountry()
    {
        return $this->country;
    }

    /**
     * Set description
     *
     * @param text $description
     */
    public function setDescription($description)
    {
        $this->description = $description;
    }

    /**
     * Get description
     *
     * @return text
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Get event date
     *
     * @return datetime
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * Set activity date
     *
     * @param datetime $date
     */
    public function setDate($date)
    {
        $this->date = $date;
    }

    /**
     * @ORM\PrePersist
     */
    public function setDefaultValues()
    {
        $this->setCountry(self::DEFAULT_COUNTRY);
    }

}

src/dcastello/TraventyBundle/Entity/ImageActivity.php
<?php

namespace dcastello\TraventyBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * dcastello\TraventyBundle\Entity\Image
 *
 * @ORM\Table(name="image_activity")
 * @ORM\Entity(repositoryClass="dcastello\TraventyBundle\Entity\ImageActivityRepository")
 * @ORM\HasLifecycleCallbacks
 */
class ImageActivity
{
    /**
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;
    /**
     * @ORM\Column(name="image", type="string", length=255)
     * @Assert\Image(maxSize="500k")
     */
    private $image;
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $name;
    /**
     * @ORM\ManyToOne(targetEntity="Activity", inversedBy="images") 
     */
    private $activity;

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }
    
    public function getName()
    {
        return $this->name;
    }

    public function setName($name)
    {
        $this->name = $name;
    }

    public function getActivity()
    {
        return $this->activity;
    }

    public function setActivity($activity)
    {
        $this->activity = $activity;
    }

    public function getImage()
    {
        return $this->image;
    }

    public function setImage($image)
    {
        $this->image = $image;
    }

    public function getUploadDir()
    {
        return 'uploads/images/activity';
    }

    public function getUploadRootDir()
    {
        return __DIR__ . '/../../../../web/' . $this->getUploadDir();
    }

    public function getWebPath()
    {
        return null == $this->name ? null : $this->getUploadDir() . '/' . $this->name;
    }

    public function getAbsolutePath()
    {
        return null == $this->name ? null : $this->getUploadRootDir() . '/' . $this->name;
    }

    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function preUpload()
    {
        if (null !== $this->image) {
            $this->name = uniqid("activity-") . '-image.' . $this->image->guessExtension();
        }
    }

    /**
     * @ORM\PostPersist()
     * @ORM\PostUpdate() 
     */
    public function upload()
    {
        if (null === $this->image) {
            return;
        }

        $this->image->move($this->getUploadRootDir(), $this->name);

        unset($this->image);
    }

    /**
     * @ORM\PostRemove() 
     */
    public function removeUpload()
    {
        if ($photo = $this->getAbsolutePath()) {
            unlink($photo);
        }
    }

}

src/dcastello/TraventyBundle/Entity/Travel.php
<?php

namespace dcastello\TraventyBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * dcastello\TraventyBundle\Entity\AgencyEvent
 * 
 * @ORM\Table(name="travel")
 * @ORM\Entity(repositoryClass="dcastello\TraventyBundle\Entity\TravelRepository")
 */
class Travel extends Event
{
    /**
     * @var string $date
     *
     * @ORM\Column(name="date", type="datetime", length=255, nullable=true)
     * @Assert\DateTime
     */
    private $date;
    /**
     * @var integer $price
     *
     * @ORM\Column(name="price", type="integer", nullable=true)
     */
    private $price;
    /**
     * @var integer $attendantLimit
     *
     * @ORM\Column(name="attendantLimit", type="integer")
     * @Assert\Min(limit="0", message="The minimum value is 0")
     */
    private $attendantLimit;
    /**
     * @ORM\ManyToOne(targetEntity="Agency", inversedBy="travels")
     * @ORM\JoinColumn(name="agency_id", referencedColumnName="id")
     */
    private $agency;
    /**
     * @ORM\OneToMany(targetEntity="TravelSubscription", mappedBy="travel", cascade={"all"})
     */
    private $subscriptions;
    
    public function __construct()
    {
        parent::__construct();
        $this->subscriptions = new ArrayCollection();
    }
    
    public function getAgency()
    {
        return $this->agency;
    }

    public function setAgency(Agency $agency = null)
    {
        $this->agency = $agency;
    }

    /**
     * Set date
     *
     * @param string $date
     */
    public function setDate($date)
    {
        $this->date = $date;
    }

    /**
     * Get date
     *
     * @return string 
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * Set price
     *
     * @param integer $price
     */
    public function setPrice($price)
    {
        $this->price = $price;
    }

    /**
     * Get price
     *
     * @return integer 
     */
    public function getPrice()
    {
        return $this->price;
    }
    
    /**
     * Set attendantLimit
     *
     * @param integer $attendantLimit
     */
    public function setAttendantLimit($attendantLimit)
    {
        $this->attendantLimit = $attendantLimit;
    }

    /**
     * Get attendantLimit
     *
     * @return integer 
     */
    public function getAttendantLimit()
    {
        return $this->attendantLimit;
    }    

    public function getSubscriptions()
    {
        return $this->subscriptions;
    }

    public function setSubscriptions($subscriptions)
    {
        $this->subscriptions = $subscriptions;
    }
    
    public function getSubscriptors()
    {
        //$this->travelSubscriptionRepository->findByTravel($this);
        return array();
    }
    
    public function getType()
    {
        return 'TRAVEL';
    }

}

src/dcastello/TraventyBundle/Entity/Traveler.php
<?php

namespace dcastello\TraventyBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * dcastello\TraventyBundle\Entity\Traveler
 * 
 * @ORM\Table(name="traveler")
 * @ORM\Entity(repositoryClass="dcastello\TraventyBundle\Entity\TravelerRepository")
 */
class Traveler extends User
{
    /**
     * @ORM\ManyToMany(targetEntity="Activity", inversedBy="favoritesTravelers")
     * @ORM\JoinTable(name="favorites_activities")
     */
    private $favoritesActivities;
    /**
     * @ORM\ManyToMany(targetEntity="Resource", inversedBy="favoritesTravelers")
     * @ORM\JoinTable(name="favorites_resources")
     */
    private $favoritesResources;
    /**
     * @ORM\OneToMany(targetEntity="Excursion", mappedBy="traveler", cascade={"persist", "remove"})
     */
    private $excursions;
    /**
     * @ORM\OneToMany(targetEntity="TravelSubscription", mappedBy="traveler", cascade={"all"})
     */
    private $subscriptions;
    /**
     * @ORM\Column(name="surname", type="string", length=100) 
     * @Assert\NotBlank()
     * @Assert\MinLength(
     *     limit=3,
     *     message="Your surname must have at least {{ limit }} characters",
     *     groups={"basicInfo"}
     * )
     */
    private $surname;
    /**
     * @ORM\Column(name="birthday", type="datetime", nullable=true) 
     * @Assert\DateTime(groups={"basicInfo"})
     */
    private $birthday;
    /**
     * @ORM\Column(name="nif", type="string", length=9, nullable=true)
     * @Assert\MinLength(
     *     limit=9,
     *     message="Min length 9 characters",
     *     groups={"basicInfo"}
     * )
     */
    private $nif;

    public function __construct()
    {
        $this->favoritesActivities = new ArrayCollection();
        $this->favoritesResources = new ArrayCollection();
        $this->excursions = new ArrayCollection();
        $this->travels = new ArrayCollection();
        $this->subscriptions = new ArrayCollection();
    }
    
    public function __toString()
    {
        return $this->getFullName();
    }
    
    public function getFullName()
    {
        return $this->getName().' '.$this->getSurname();
    }

    /**
     * Set nif
     *
     * @param string $nif
     */
    public function setNif($nif)
    {
        $this->nif = $nif;
    }

    /**
     * Get CIF
     * 
     * @return string
     */
    public function getNif()
    {
        return $this->nif;
    }

    /**
     *
     * @param string $surname 
     */
    public function setSurname($surname)
    {
        $this->surname = $surname;
    }

    /**
     *
     * @return string
     */
    public function getSurname()
    {
        return $this->surname;
    }

    /**
     *
     * @param datetime $birthday 
     */
    public function setBirthday($birthday)
    {
        $this->birthday = $birthday;
    }

    public function getBirthday()
    {
        return $this->birthday;
    }

    public function getFavoritesActivities()
    {
        return $this->favoritesActivities;
    }

    public function addFavoriteActivity(Activity $activity)
    {
        if (!$this->favoritesActivities->contains($activity)) {
            $activity->addFavoriteTraveler($this);
            $this->favoritesActivities->add($activity);
        }
    }

    public function getFavoritesResources()
    {
        return $this->favoritesResources;
    }

    public function addFavoriteResource(Resource $resource)
    {
        if (!$this->favoritesResources->contains($resource)) {
            $resource->addFavoriteTraveler($this);
            $this->favoritesResources->add($resource);
        }
    }

    public function getExcursions()
    {
        return $this->excursions;
    }

    public function addExcursion(Excursion $excursion)
    {
        if (!$this->excursions->contains($excursion)) {
            $this->excursions->add($excursion);
            $excursion->setTraveler($this);
        }
    }

    public function removeExcursion(Excursion $excursion)
    {
        if ($this->excursions->contains($excursion)) {
            $this->excursions->removeElement($excursion);
            $excursion->setTraveler(null);
        }
    }
    
    public function getSubscriptions()
    {
        return $this->subscriptions;
    }
    
    public function setSubscriptions($subscriptions)
    {
        $this->subscriptions = $subscriptions;
    }    
    
    function getRoles()
    {
        return array('ROLE_TRAVELER');
    }

    function getType()
    {
        return 'TRAVELER';
    }

}

src/dcastello/TraventyBundle/Form/TravelType.php
<?php

namespace dcastello\TraventyBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilder;

class TravelType extends AbstractType
{
    public function buildForm(FormBuilder $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('active')
            ->add('date','date', array(
                'widget' => 'choice',
                'years'  => range(date("Y"),date("Y") + 6)
            ))
            ->add('price', 'money')
            ->add('attendantLimit', 'integer', array(
                'label' => 'Attendant limit'
            ))
        ;
    }

    public function getName()
    {
        return 'agencyTravel';
    }
}

src/dcastello/TraventyBundle/Resources/views/Travel/detailTravel.html.twig
{% extends 'TraventyBundle::layout.html.twig' %}

{% block id 'travels' %}

{% block javascripts %}
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript" ></script>
   <script src="{{ asset('bundles/traventy/bootstrap/js/bootstrap.min.js') }}" type="text/javascript" ></script>
   <script src="{{ asset('bundles/traventy/bootstrap/js/bootstrap-carusel.js') }}" type="text/javascript" ></script>
   <script src="{{ asset('bundles/traventy/js/travels.js') }}" type="text/javascript" ></script>
{% endblock %}

{% block content %}

<div class="row">

   <div class="span12">  
   <h2>{{ travel.name|capitalize }}</h2>
   
   <div class="well">
    <div class="row">
        <div class="span3">
            <p><i class="icon-user"></i> {{ travel.agency.username|capitalize }}</p>
        </div>
        <div class="span3">
            <p><i class="icon-info-sign"></i> Prize: <strong>{{ travel.price|default('Not introduced') }}</strong></p>
        </div>
        <div class="span3">
            <p><i class="icon-exclamation-sign"></i> Attendants limit: <strong>{{ travel.attendantLimit }}</strong></p>
        </div>            
        {% if is_granted('ROLE_TRAVELER') %}
        <div class="span2">
            <a href="{{ path('agency_travel_add_attendant', { 'username': travel.agency.username, 'travelid': travel.id}) }}" 
               class="btn btn-primary btn-small pull-right" title="Subscribe to the travel!">
            <i class="icon-hand-right icon-white"></i> Subscribe!</a>
        </div>
        {% elseif not is_granted('IS_AUTHENTICATED_FULLY') %}
            <a href="#" rel="popover" data-original-title="Travel"
               data-content="Only Travelers can subscribe"
               class="btnsubscribe btn btn-primary btn-small pull-right" title="Subscribe to the travel!">
            <i class="icon-hand-right icon-white"></i> Subscribe!</a>
        {% endif %}
    </div>
   </div>
   
   {% include 'TraventyBundle:Default:alerts.html.twig' %}
   
   <div class="tabbable">
      <ul class="nav nav-tabs">
         <li class="active"><a href="#travelActivities" data-toggle="tab">Activities</a></li>
         <li><a href="#travelResources" data-toggle="tab">Resources</a></li>
         <li><a href="#travelSubscribers" data-toggle="tab">Subcribers</a></li>
      </ul>
      <div class="tab-content">
         <div class="tab-pane active" id="travelActivities">
            
         <ul class="thumbnails">
         {% for activity in travel.activities %}
            <li class="span3">
               <div class="thumbnail">

                  <a href="{{ path('activity_show', {'id' : activity.id}) }}">
                  {% if activity.randomImage is not null %}
                      <img src="{{ asset(activity.randomImage.webPath) | apply_filter('thumb_210x120') }}" />
                  {% else %}
                      <img src="{{ asset('bundles/traventy/images/' ~ no_image120) }}" />
                  {% endif %}
                  </a>
                  <div class="caption">
                     <h4>
                     <a href="{{ path('activity_show', {'id' : activity.id}) }}">{{ activity.name }}</a>
                     </h4>
                     <p><strong>{{ activity.city }}</strong><br />({{ activity.city.state }})</p>
                  </div>

               </div>
            </li>
         {% else %}
            <li><div class="alert alert-info">Ups! There aren't activities for this travel</div></li>
         {% endfor %}
         </ul>            
            
         </div>
            
         <div class="tab-pane" id="travelResources">
            
         <ul class="thumbnails">
         {% for resource in travel.resources %}
            <li class="span3">
               <div class="thumbnail">

                  <a href="{{ path('resource_show', {'id' : resource.id}) }}">
                  <img src="{{ asset('bundles/traventy/images/' ~ no_image120) }}" />
                  </a>
                  <div class="caption">
                     <h4>
                     <a href="{{ path('resource_show', {'id' : resource.id}) }}">{{ resource.name }}</a>
                     </h4>
                     <p><strong>{{ resource.city }}</strong><br />({{ resource.city.state }})</p>
                  </div>

               </div>
            </li>
         {% else %}
            <li><div class="alert alert-info">Ups! There aren't resources for this travel</div></li>            
         {% endfor %}
         </ul>            
            
         </div>
              
         <div class="tab-pane" id="travelSubscribers">
            
         <ul class="thumbnails">
         {% for subscriptor in acceptedSubscriptions %}
            <li class="span3">
               <div class="thumbnail">
                   <i class="icon-user"></i> {{ subscriptor.name }}
               </div>
            </li>
         {% else %}
            <li><div class="alert alert-info">Ups! There aren't subscriptions for this travel</div></li>            
         {% endfor %}
         </ul>
            
         </div>
              
      </div>
   </div>     
      
   <ul class="nav nav-pills pull-right">
       <li><a href="{{ path('travels') }}" class="btn btn-small" title="Back to travel list">
           <i class="icon-list"></i> Back to list</a></li>
       {% if is_granted('ROLE_TRAVELER') %}
       <li><a href="" class="btn btn-primary btn-small" title="Subscribe to the travel!">
           <i class="icon-hand-right icon-white"></i> Subscribe!</a></li>
       {% elseif not is_granted('IS_AUTHENTICATED_FULLY') %}
       <li><a href="#" rel="popover" data-original-title="Travel"
              data-content="Only Travelers can subscribe"
              class="btnsubscribe btn btn-primary btn-small pull-right" title="Subscribe to the travel!">
           <i class="icon-hand-right icon-white"></i> Subscribe!</a></li>
       {% endif %}
   </ul>
   
   </div>
</div>

{% endblock %}

src/dcastello/TraventyBundle/Resources/views/Travel/showTravel.html.twig
{% extends 'TraventyBundle::layout.html.twig' %}

{% block id 'event' %}

{% block content %}

<div class="row">
   <div class="span3">
      {% include 'TraventyBundle:Default:menuBackend.html.twig' %}
   </div>        

   <div class="span9">  
   <h3>{{ travel.name|capitalize }}</h3>
     
   <div class="tabbable">
      <ul class="nav nav-tabs">
         <li class="active"><a href="#travelActivities" data-toggle="tab">Activities</a></li>
         <li><a href="#travelResources" data-toggle="tab">Resources</a></li>
         <li><a href="#travelSubscribers" data-toggle="tab">Subscribers</a></li>
      </ul>
      <div class="tab-content">
         <div class="tab-pane active" id="travelActivities">
            
         <ul class="thumbnails">
         {% for activity in travel.activities %}
            <li class="span3">
               <div class="thumbnail">

                  <a href="{{ path('activity_show', {'id' : activity.id}) }}">
                  <img src="{{ asset('bundles/traventy/images/' ~ no_image120) }}" />
                  </a>
                  <div class="caption">
                     <h4>
                     <a href="{{ path('activity_show', {'id' : activity.id}) }}">{{ activity.name }}</a>
                     </h4>
                          <p><strong>{{ activity.city }}</strong><br />({{ activity.city.state }})</p>
                     <a class="btn btn-mini" href="{{ path('travel_remove_activity',{
                        'username' : app.user.username,
                        'travelid' : travel.id,
                        'activityid' : activity.id
                     })  }}" >
                     <i class="icon-remove"></i> Remove</a>                     
                  </div>

               </div>
            </li>
         {% else %}
            <li><div class="alert alert-info">Ups! There aren't activities for this travel</div></li>
         {% endfor %}
         </ul>            
            
         </div>
            
         <div class="tab-pane" id="travelResources">
            
         <ul class="thumbnails">
         {% for resource in travel.resources %}
            <li class="span3">
               <div class="thumbnail">

                  <a href="{{ path('resource_show', {'id' : travel.id}) }}">
                  <img src="{{ asset('bundles/traventy/images/' ~ no_image120) }}" />
                  </a>
                  <div class="caption">
                     <h4>
                     <a href="{{ path('resource_show', {'id' : resource.id}) }}">{{ resource.name }}</a>
                     </h4>
                          <p><strong>{{ resource.city }}</strong><br />({{ resource.city.state }})</p>
                     <a class="btn btn-mini" href="{{ path('travel_remove_resource',{
                        'username' : app.user.username,
                        'travelid' : travel.id,
                        'resourceid' : resource.id
                     })  }}" >
                     <i class="icon-remove"></i> Remove</a>                     

                  </div>

               </div>
            </li>
         {% else %}
            <li><div class="alert alert-info">Ups! There aren't resources for this travel</div></li>
         {% endfor %}
         </ul>            
            
         </div>
              
         <div class="tab-pane" id="travelSubscribers">
         
         <h4>Pending Subscriptions</h4>
         <ul class="thumbnails">
         {% for subscription in pendingSubscriptions %}
            <li class="span3">
               <div class="thumbnail">

                  <div class="caption">
                     <p>{{ subscription.traveler.fullName }} <br /><strong>@{{ subscription.traveler.username }}</strong></p>

                     <a class="btn btn-mini" href="{{ path('travel_subscription_accept', {
                        'username' : app.user.username,
                        'travelid' : subscription.travel.id,
                        'travelerusername' : subscription.traveler.username                        
                     }) }}" >
                     <i class="icon-thumbs-up"></i> Accept</a>
                     <a class="btn btn-mini" href="{{ path('travel_subscription_deny', {
                        'username' : app.user.username,
                        'travelid' : subscription.travel.id,
                        'travelerusername' : subscription.traveler.username                        
                     }) }}" >
                     <i class="icon-thumbs-down"></i> Deny</a>
                     
                  </div>                   

               </div>
            </li>
         {% else %}
            <li><div class="alert alert-info">Ups! There aren't pending subscriptions for this travel</div></li>
         {% endfor %}
         </ul>
         
         <h4>Accepted Subscriptions</h4>
         <ul class="thumbnails">
         {% for subscription in acceptedSubscriptions %}
            <li class="span3">
               <div class="thumbnail">
                  
                  <div class="caption">
                     <p>{{ subscription.traveler.fullName }} <br /><strong>@{{ subscription.traveler.username }}</strong></p>

                     <a class="btn btn-mini" href="{{ path('travel_subscription_deny', {
                        'username' : app.user.username,
                        'travelid' : subscription.travel.id,
                        'travelerusername' : subscription.traveler.username                        
                     }) }}" >
                     <i class="icon-thumbs-down"></i> Deny</a>
                     
                  </div>

               </div>
            </li>
         {% else %}
            <li><div class="alert alert-info">Ups! There aren't accepted subscriptions for this travel</div></li>
         {% endfor %}
         </ul>
            
         <h4>Denied Subscriptions</h4>
         <ul class="thumbnails">
         {% for subscription in deniedSubscriptions %}
            <li class="span3">
               <div class="thumbnail">
                  
                  <div class="caption">
                     <p>{{ subscription.traveler.fullName }} <br /><strong>@{{ subscription.traveler.username }}</strong></p>

                     <a class="btn btn-mini" href="{{ path('travel_subscription_accept', {
                        'username' : app.user.username,
                        'travelid' : subscription.travel.id,
                        'travelerusername' : subscription.traveler.username                        
                     }) }}" >
                     <i class="icon-thumbs-up"></i> Accept</a>
                     
                  </div>                   

               </div>
            </li>
         {% else %}
            <li><div class="alert alert-info">Ups! There aren't denied subscriptions for this travel</div></li>
         {% endfor %}
         </ul>
         
         </div>
              
      </div>
   </div>     
      
   <ul class="nav nav-pills pull-right">
     <li><a class="btn btn-small" href="{{ path('agency_travels', { 'username': app.user.username }) }}">Back to list</a></li>
     <li><a class="btn btn-small btn-danger" href="{{ path('agency_delete_travel', 
         {'username' : app.user.username, 'id' : travel.id }) }}">
         <i class="icon-trash icon-white"></i> Delete</a></li>
   </ul>
   
   </div>
</div>

{% endblock %}

{% block javascripts %}

   <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript" /></script>
   <script src="{{ asset('bundles/traventy/bootstrap/js/bootstrap.min.js') }}" type="text/javascript" /></script>

{% endblock %}

src/dcastello/TraventyBundle/Resources/views/Travel/travels.html.twig
{% extends "TraventyBundle::layout.html.twig" %}

{% block id 'excursions' %}

{% block content %}

<h2>Travels list</h2>

<div class="row">
  <div class="span12">
    <ul class="thumbnails">        
      {% for travel in travels %}
      <li class="span3">
        <div class="thumbnail">
          <img src="{{ asset('bundles/traventy/images/home-image.png') }}" height="90px" width="90px" alt="" />
          <h5>
          <a href="{{ path('agency_detail_travel', {'id' : travel.id, 'username' : travel.agency.username }) }}" title="">{{ travel.name }}</a>
          </h5>
          <p>(Activities: {{ travel.activities.count }} - Resources: {{ travel.resources.count }})</p>
        </div>
      </li>
      {% endfor %}
    </ul>
  </div>
</div>

{% endblock %}